#!/usr/bin/env python3
"""Compile fg22_algo.c and generate target_EFR32FG22C121F512GM40.py (a pyOCD builtin-style target with the flash algorithm).

usage: build_algo.py            (needs Homebrew LLVM: brew install llvm; override with LLVM_BIN)
"""
import os, re, struct, subprocess, sys, textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
LLVM = os.environ.get("LLVM_BIN", "/opt/homebrew/opt/llvm/bin")
SRC = os.path.join(HERE, "fg22_algo.c")
OBJ = os.path.join(HERE, "fg22_algo.o")
OUT = os.path.join(HERE, "target_EFR32FG22C121F512GM40.py")

LOAD = 0x20000000
STACK_TOP = 0x20000700           # stack grows down from here, below the page buffers
PAGE_BUFS = [0x20000800, 0x20000C00]
PAGE_SIZE = 0x400                # programming chunk; divides the 8 KiB erase page

def run(*cmd):
    return subprocess.run(cmd, check=True, capture_output=True, text=True).stdout

run(f"{LLVM}/clang", "--target=thumbv8m.main-none-eabi", "-mcpu=cortex-m33", "-Os", "-ffreestanding", "-fno-builtin", "-fno-pic",
    "-fno-unwind-tables", "-fno-asynchronous-unwind-tables", "-nostdlib", "-Wall", "-Wextra", "-c", SRC, "-o", OBJ)
if "'.rel.text'" in run(f"{LLVM}/llvm-readelf", "-r", OBJ):
    sys.exit("algorithm has relocations in .text; it must be position independent")
binf = OBJ + ".bin"
run(f"{LLVM}/llvm-objcopy", "-O", "binary", "-j", ".text", OBJ, binf)
code = open(binf, "rb").read()
code += b"\x00" * (-len(code) % 4)

syms = {}
for line in run(f"{LLVM}/llvm-nm", "--defined-only", OBJ).splitlines():
    m = re.match(r"([0-9a-f]+)\s+[tT]\s+(\w+)", line)
    if m: syms[m.group(2)] = int(m.group(1), 16)
for need in ("Init", "UnInit", "EraseSector", "ProgramPage"):
    if need not in syms: sys.exit(f"missing symbol {need}")

HDR = 4                                   # first word: BKPT trap pyOCD returns to
image = struct.pack("<I", 0xE7FDBE00) + code
words = list(struct.unpack(f"<{len(image)//4}I", image))
pc = {k: LOAD + HDR + off + 1 for k, off in syms.items()}      # +1: Thumb
static_base = LOAD + len(image)
assert static_base < STACK_TOP - 0x40 and len(image) < 0x600, "algorithm too large for its RAM slot"

def fmt(ws):
    lines = []
    for i in range(0, len(ws), 8):
        lines.append("        " + ", ".join(f"0x{w:08x}" for w in ws[i:i+8]) + ",")
    return "\n".join(lines)

target = f'''# pyOCD target for the Silicon Labs EFR32FG22C121F512GM40 (Series 2, Cortex-M33; 512 KiB flash, 32 KiB RAM).
#
# Generated by pyocd-target/build_algo.py from fg22_algo.c -- edit the C file, not the words below.
# The flash algorithm drives the MSC (flash controller) the way Silicon Labs' em_msc.c does for Series 2.
#
# SPDX-License-Identifier: Apache-2.0

from ...coresight.coresight_target import CoreSightTarget
from ...core.memory_map import FlashRegion, RamRegion, MemoryMap

FLASH_ALGO = {{
    'load_address' : 0x{LOAD:08x},

    # Flash algorithm as a hex string
    'instructions': [
{fmt(words)}
    ],

    # Relative function addresses
    'pc_init': 0x{pc["Init"]:08x},
    'pc_unInit': 0x{pc["UnInit"]:08x},
    'pc_program_page': 0x{pc["ProgramPage"]:08x},
    'pc_erase_sector': 0x{pc["EraseSector"]:08x},

    'static_base' : 0x{static_base:08x},
    'begin_stack' : 0x{STACK_TOP:08x},
    'end_stack' : 0x{STACK_TOP - 0x100:08x},
    'page_size' : 0x{PAGE_SIZE:x},
    'analyzer_supported' : False,
    'analyzer_address' : 0x00000000,
    # Double buffering
    'page_buffers' : [
        0x{PAGE_BUFS[0]:08x},
        0x{PAGE_BUFS[1]:08x},
    ],
    'min_program_length' : 4,
}}


class EFR32FG22C121F512GM40(CoreSightTarget):

    VENDOR = "Silicon Labs"

    MEMORY_MAP = MemoryMap(
        FlashRegion(start=0x00000000, length=0x80000, page_size=0x{PAGE_SIZE:x}, sector_size=0x2000,
                    is_boot_memory=True, algo=FLASH_ALGO),
        RamRegion(start=0x20000000, length=0x8000),
    )

    def __init__(self, session):
        super().__init__(session, self.MEMORY_MAP)
'''
open(OUT, "w").write(target)

# Standalone launcher: same target with absolute imports, registered into pyOCD at runtime, then runs the normal pyocd CLI.
standalone = (target
    .replace("from ...coresight.coresight_target import", "from pyocd.coresight.coresight_target import")
    .replace("from ...core.memory_map import", "from pyocd.core.memory_map import")
    + '''

# --- runtime registration (only in the standalone launcher; upstream targets are registered in pyocd/target/builtin/__init__.py) ---
from pyocd.target import TARGET
TARGET["efr32fg22c121f512gm40"] = EFR32FG22C121F512GM40

if __name__ == "__main__":
    import sys
    from pyocd.__main__ import PyOCDTool
    sys.exit(PyOCDTool().run())
''')
open(os.path.join(HERE, "pyocd_fg22.py"), "w").write(standalone)
print(f"wrote {OUT}: {len(image)} byte algorithm; Init {pc['Init']:#x} UnInit {pc['UnInit']:#x} Erase {pc['EraseSector']:#x} Program {pc['ProgramPage']:#x}")
