# pyOCD target for the Silicon Labs EFR32FG22C121F512GM40 (Series 2, Cortex-M33; 512 KiB flash, 32 KiB RAM).
#
# Generated by pyocd-target/build_algo.py from fg22_algo.c -- edit the C file, not the words below.
# The flash algorithm drives the MSC (flash controller) the way Silicon Labs' em_msc.c does for Series 2.
#
# SPDX-License-Identifier: Apache-2.0

from ...coresight.coresight_target import CoreSightTarget
from ...core.memory_map import FlashRegion, RamRegion, MemoryMap

FLASH_ALGO = {
    'load_address' : 0x20000000,

    # Flash algorithm as a hex string
    'instructions': [
        0xe7fdbe00, 0x0068f248, 0x0000f2c4, 0xf4416801, 0x60013100, 0xf2c4210c, 0xf6410103, 0x63083071,
        0xf0406808, 0x20000201, 0x4770600a, 0xf2c4210c, 0x68080103, 0xf0202200, 0x60080001, 0x630a2000,
        0xf2404770, 0x21000c10, 0x0c03f2c4, 0x71c0f6cf, 0x0004f8cc, 0xf8cc2002, 0x46080000, 0x300cf8dc,
        0xd40a075a, 0x0f21f013, 0x3001d002, 0xe004d3f6, 0xf2c02002, 0x42030001, 0x2001d007, 0xbf004770,
        0x0f21f013, 0x3101d006, 0xf8dcd2f7, 0x075a300c, 0xe7f5d4f3, 0xbf184018, 0x47702001, 0x2310b570,
        0x0303f2c4, 0x68d86058, 0xd4330740, 0xd0120889, 0x68152000, 0x70c0f6cf, 0x609d2901, 0x2104d10d,
        0x46016019, 0x075668da, 0xf012d424, 0xd0230f21, 0xd21f3101, 0x2000e7f6, 0xf240bd70, 0xf04f0e02,
        0xf2c00c01, 0x32040e01, 0xbf004604, 0x076e68dd, 0x072ed40e, 0x3401d402, 0xe7f7d20a, 0x0f0eea15,
        0x6814d106, 0x0c01f10c, 0x609c458c, 0xe7d6d1eb, 0x60182004, 0xbd702001, 0xf2c02102, 0x420a0101,
        0xe7f7d005, 0x0f21f012, 0x3001d005, 0x68dad2f2, 0xd4ef0756, 0xea12e7f6, 0xbf180001, 0xbd702001,
    ],

    # Relative function addresses
    'pc_init': 0x20000005,
    'pc_unInit': 0x2000002d,
    'pc_program_page': 0x2000009d,
    'pc_erase_sector': 0x20000043,

    'static_base' : 0x20000140,
    'begin_stack' : 0x20000700,
    'end_stack' : 0x20000600,
    'page_size' : 0x400,
    'analyzer_supported' : False,
    'analyzer_address' : 0x00000000,
    # Double buffering
    'page_buffers' : [
        0x20000800,
        0x20000c00,
    ],
    'min_program_length' : 4,
}


class EFR32FG22C121F512GM40(CoreSightTarget):

    VENDOR = "Silicon Labs"

    MEMORY_MAP = MemoryMap(
        FlashRegion(start=0x00000000, length=0x80000, page_size=0x400, sector_size=0x2000,
                    is_boot_memory=True, algo=FLASH_ALGO),
        RamRegion(start=0x20000000, length=0x8000),
    )

    def __init__(self, session):
        super().__init__(session, self.MEMORY_MAP)
